from __future__ import annotations

import os
from datetime import datetime

from .common import SourceSpec, collect_source_specs


TIER2_SPECS: list[SourceSpec] = [
    SourceSpec(
        source_id="tier2_the_national",
        name="The National UAE",
        url="https://www.thenationalnews.com/uae/",
        tier="TIER2",
        indicator_ids=("I06",),
        keywords=("fuel", "supply", "supermarket", "stock", "panic buying", "shortage"),
        critical_keywords=("shortage", "empty shelves", "rationing"),
        interval_min=60,
        priority="high",
        collection_target="UAE 연료·식료품 재고 상태",
    ),
    SourceSpec(
        source_id="tier2_khaleej_times",
        name="Khaleej Times",
        url="https://www.khaleejtimes.com/",
        tier="TIER2",
        indicator_ids=("I06",),
        keywords=("fuel", "supply", "stock", "rationing", "shortage", "supermarket"),
        critical_keywords=("rationing", "shortage", "empty shelves"),
        interval_min=60,
        priority="high",
        collection_target="UAE 연료·식료품 재고 상태",
    ),
    SourceSpec(
        source_id="tier2_gulf_news",
        name="Gulf News",
        url="https://gulfnews.com/",
        tier="TIER2",
        indicator_ids=("I06",),
        keywords=("fuel", "food", "supply", "stock", "supermarket", "shortage"),
        critical_keywords=("shortage", "rationing", "panic buying"),
        interval_min=60,
        priority="high",
        collection_target="슈퍼마켓 품절 품목 보고",
    ),
    SourceSpec(
        source_id="tier2_adnoc_distribution",
        name="ADNOC Distribution",
        url="https://www.adnocdistribution.ae/",
        tier="TIER2",
        indicator_ids=("I06",),
        keywords=("fuel", "prices", "stations", "service", "supply"),
        critical_keywords=("price", "supply disruption"),
        interval_min=60,
        priority="medium",
        collection_target="연료 가격 (ADNOC)",
    ),
    SourceSpec(
        source_id="tier2_enoc",
        name="ENOC",
        # enoc.com blocks automated clients; Google News RSS indexed to enoc.com is stable
        url="https://news.google.com/rss/search?q=site:enoc.com+fuel+price+UAE&hl=en-AE&gl=AE&ceid=AE:en",
        tier="TIER2",
        indicator_ids=("I06",),
        keywords=("fuel", "prices", "stations", "service", "supply"),
        critical_keywords=("price", "supply disruption"),
        interval_min=60,
        priority="medium",
        collection_target="연료 가격 (ENOC)",
    ),
    SourceSpec(
        source_id="tier2_waze_live_map",
        name="Waze Live Map",
        url="https://www.waze.com/live-map/",
        tier="TIER2",
        indicator_ids=("I04",),
        keywords=("traffic", "jam", "congestion", "road", "incident", "closed"),
        critical_keywords=("road closed", "blocked", "congested"),
        tags=("route_a_congested",),
        interval_min=15,
        priority="critical",
        collection_target="Al Ain 국경 혼잡도",
    ),
    SourceSpec(
        source_id="tier2_google_maps_traffic",
        name="Google Maps Traffic",
        url="https://www.google.com/maps",
        tier="TIER2",
        indicator_ids=("I04",),
        keywords=("traffic", "congestion", "incident", "closed", "border"),
        critical_keywords=("closed", "congestion"),
        tags=("route_a_congested", "route_b_congested"),
        interval_min=15,
        priority="high",
        collection_target="Al Ain 국경 혼잡도",
    ),
    SourceSpec(
        source_id="tier2_oman_border",
        name="Royal Oman Police Border",
        url="https://www.rop.gov.om/",
        tier="TIER2",
        indicator_ids=("I04",),
        keywords=("border", "crossing", "opening hours", "restricted", "closed"),
        critical_keywords=("closed", "restricted", "border closed"),
        tags=("border_watch", "route_b_congested"),
        interval_min=30,
        priority="critical",
        collection_target="Buraimi/Nizwa 국경 통과 시간",
    ),
    SourceSpec(
        source_id="tier2_uae_icp_border",
        name="UAE ICP",
        url="https://icp.gov.ae/en/",
        tier="TIER2",
        indicator_ids=("I04",),
        keywords=("border", "entry", "exit", "crossing", "announcement"),
        critical_keywords=("border closed", "restricted", "suspend"),
        tags=("border_watch",),
        interval_min=30,
        priority="high",
        collection_target="UAE Border Authority",
    ),
    SourceSpec(
        source_id="tier2_port_fujairah",
        name="Port of Fujairah",
        url="https://www.fujairahport.ae/",
        tier="TIER2",
        indicator_ids=("I04",),
        keywords=("operations", "port", "disruption", "closed", "marine"),
        critical_keywords=("closed", "disruption", "suspended"),
        tags=("fujairah_disruption", "route_d_blocked"),
        interval_min=60,
        priority="high",
        collection_target="Fujairah 항구 상태",
    ),
    SourceSpec(
        source_id="tier2_saudi_border",
        name="Saudi Public Security",
        # psd.gov.sa regularly times out from CI runners; SPA is consistently reachable
        url="https://www.spa.gov.sa/en",
        tier="TIER2",
        indicator_ids=("I04",),
        keywords=("border", "crossing", "security", "restricted", "closed"),
        critical_keywords=("border closed", "restricted", "security warning"),
        tags=("saudi_warning", "route_c_blocked"),
        interval_min=60,
        priority="medium",
        collection_target="사우디 국경 Ghuwaifat 상태",
    ),
]


async def collect_tier2_signals(*, timeout_sec: float, now: datetime) -> tuple[list[dict], dict[str, dict]]:
    if os.getenv("PYTEST_CURRENT_TEST"):
        return [], {}
    return await collect_source_specs(TIER2_SPECS, timeout_sec=timeout_sec, checked_at=now)
