from __future__ import annotations

import os
from datetime import datetime

from .common import SourceSpec, collect_source_specs


ALERT_KEYWORDS = (
    "uae attack",
    "iran strike",
    "border closed",
    "flight suspended",
    "evacuation",
    "do not travel",
    "ordered departure",
)


TIER1_SPECS: list[SourceSpec] = [
    SourceSpec(
        source_id="tier1_aljazeera_middle_east",
        name="Al Jazeera Middle East",
        url="https://www.aljazeera.com/news/middleeast/",
        tier="TIER1",
        indicator_ids=("I03",),
        keywords=("iran", "uae", "strike", "missile", "drone", "explosion", *ALERT_KEYWORDS),
        critical_keywords=("missile", "drone", "explosion", "uae attack", "iran strike"),
        tags=("strike",),
        interval_min=15,
        priority="critical",
        collection_target="이란 공격 보복 여부·규모",
    ),
    SourceSpec(
        source_id="tier1_reuters_world",
        name="Reuters World",
        # reuters.com returns 401 (subscription) and feeds.reuters.com DNS fails in some VMs
        # Google News RSS searches for Reuters content — publicly accessible, high quality
        url="https://news.google.com/rss/search?q=reuters+iran+uae+attack&hl=en-AE&gl=AE&ceid=AE:en",
        tier="TIER1",
        indicator_ids=("I03",),
        keywords=("iran", "uae", "missile", "drone", "attack", "gulf", "reuters", *ALERT_KEYWORDS),
        critical_keywords=("missile", "drone", "attack", "uae attack", "iran strike"),
        tags=("strike",),
        interval_min=15,
        priority="critical",
        collection_target="이란 공격 보복 여부·규모",
    ),
    SourceSpec(
        source_id="tier1_bbc_world",
        name="BBC World",
        url="https://www.bbc.com/news/world/middle_east",
        tier="TIER1",
        indicator_ids=("I03",),
        keywords=("iran", "uae", "attack", "strike", "drone", "missile", *ALERT_KEYWORDS),
        critical_keywords=("attack", "drone", "missile", "uae attack", "iran strike"),
        tags=("strike",),
        interval_min=15,
        priority="critical",
        collection_target="이란 공격 보복 여부·규모",
    ),
    SourceSpec(
        source_id="tier1_cnn_breaking",
        name="CNN Middle East",
        url="https://www.cnn.com/middleeast",
        tier="TIER1",
        indicator_ids=("I03",),
        keywords=("iran", "uae", "explosion", "missile", "drone", "strike", *ALERT_KEYWORDS),
        critical_keywords=("explosion", "missile", "drone", "uae attack", "iran strike"),
        tags=("strike",),
        interval_min=15,
        priority="critical",
        collection_target="걸프 지역 폭발·경보 보고",
    ),
    SourceSpec(
        source_id="tier1_cnbc_middle_east",
        name="CNBC Middle East",
        url="https://www.cnbc.com/middle-east/",
        tier="TIER1",
        indicator_ids=("I03",),
        keywords=("iran", "uae", "explosion", "attack", "strike", "missile", *ALERT_KEYWORDS),
        critical_keywords=("explosion", "attack", "strike", "uae attack"),
        tags=("strike",),
        interval_min=15,
        priority="high",
        collection_target="걸프 지역 폭발·경보 보고",
    ),
    SourceSpec(
        source_id="tier1_canada_uae_advisory",
        name="Canada Travel Advisory UAE",
        url="https://travel.gc.ca/destinations/united-arab-emirates",
        tier="TIER1",
        indicator_ids=("I04",),
        keywords=("advisory", "avoid", "security", "border", "road", "restricted", *ALERT_KEYWORDS),
        critical_keywords=("avoid", "border closed", "restricted", "do not travel"),
        tags=("border_watch",),
        interval_min=30,
        priority="high",
        collection_target="UAE/사우디/오만 국경 상태",
    ),
    SourceSpec(
        source_id="tier1_timeout_abudhabi",
        name="Time Out Abu Dhabi",
        url="https://www.timeoutabudhabi.com/news",
        tier="TIER1",
        indicator_ids=("I04",),
        keywords=("road", "closure", "traffic", "alert", "border", "restricted", *ALERT_KEYWORDS),
        critical_keywords=("closure", "border closed", "restricted"),
        tags=("border_watch", "route_a_congested"),
        interval_min=30,
        priority="high",
        collection_target="UAE/사우디/오만 국경 상태",
    ),
    SourceSpec(
        source_id="tier1_ncema_alerts",
        name="UAE NCEMA",
        url="https://www.ncema.gov.ae/en/",
        tier="TIER1",
        indicator_ids=("I04",),
        keywords=("alert", "emergency", "sms", "warning", "civil defense"),
        critical_keywords=("emergency", "sms", "warning"),
        tags=("border_watch",),
        interval_min=15,
        priority="high",
        collection_target="SMS 공습경보 시스템 가동 여부",
    ),
    SourceSpec(
        source_id="tier1_downdetector_uae",
        name="Downdetector UAE",
        # downdetector.ae returns 403 (Cloudflare JS challenge — cannot bypass with httpx)
        # UAE TDRA (Telecom Regulatory Authority) is the official authority for comms incidents
        url="https://www.tdra.gov.ae/en/the-authority",
        tier="TIER1",
        indicator_ids=("I05",),
        keywords=("outage", "disruption", "internet", "network", "incident",
                  "telecom", "service", "down", "etisalat", "du"),
        critical_keywords=("outage", "major outage", "service disruption"),
        tags=("comms",),
        interval_min=15,
        priority="critical",
        collection_target="통신망 장애 (Etisalat/du)",
    ),
    SourceSpec(
        source_id="tier1_etisalat_status",
        name="e& UAE",
        url="https://www.etisalat.ae/en/",
        tier="TIER1",
        indicator_ids=("I05",),
        keywords=("service", "network", "maintenance", "outage", "incident"),
        critical_keywords=("outage", "incident"),
        tags=("comms",),
        interval_min=15,
        priority="high",
        collection_target="통신망 장애 (Etisalat)",
    ),
    SourceSpec(
        source_id="tier1_du_status",
        name="du UAE",
        url="https://www.du.ae/",
        tier="TIER1",
        indicator_ids=("I05",),
        keywords=("service", "network", "maintenance", "outage", "incident"),
        critical_keywords=("outage", "incident"),
        tags=("comms",),
        interval_min=15,
        priority="high",
        collection_target="통신망 장애 (du)",
    ),
    SourceSpec(
        source_id="tier1_aws_status",
        name="AWS Service Health",
        url="https://status.aws.amazon.com/",
        tier="TIER1",
        indicator_ids=("I05",),
        keywords=("degraded", "outage", "service event", "operational", "region"),
        critical_keywords=("degraded", "outage", "service event"),
        tags=("comms",),
        interval_min=15,
        priority="critical",
        collection_target="AWS UAE 리전 상태",
    ),
    SourceSpec(
        source_id="tier1_azure_status",
        name="Azure Status",
        # azure.status.microsoft.com fails DNS resolution in some VM environments
        # CDN feed URL resolves reliably and provides the same status data as RSS
        url="https://azurestatuscdn.azureedge.net/en-us/status/feed/",
        tier="TIER1",
        indicator_ids=("I05",),
        keywords=("degraded", "outage", "service issue", "incident", "middle east",
                  "disruption", "impact", "uae", "impacted"),
        critical_keywords=("degraded", "outage", "incident"),
        tags=("comms",),
        interval_min=15,
        priority="critical",
        collection_target="Azure UAE 리전 상태",
    ),
    SourceSpec(
        source_id="tier1_nation_thailand",
        name="Nation Thailand",
        url="https://www.nationthailand.com/",
        tier="TIER1",
        indicator_ids=("I07",),
        keywords=("evacuation", "middle east", "uae", "military flight", *ALERT_KEYWORDS),
        critical_keywords=("evacuation", "military flight"),
        interval_min=30,
        priority="high",
        collection_target="태국 대피 현황",
    ),
    SourceSpec(
        source_id="tier1_ndtv_world",
        name="NDTV World",
        url="https://www.ndtv.com/world-news",
        tier="TIER1",
        indicator_ids=("I07",),
        keywords=("evacuation", "special flight", "uae", "middle east", *ALERT_KEYWORDS),
        critical_keywords=("evacuation", "special flight"),
        interval_min=30,
        priority="high",
        collection_target="인도 대피 현황",
    ),
    SourceSpec(
        source_id="tier1_manila_times",
        name="Rappler Philippines",
        # manilatimes.net returns 403 (Cloudflare JS challenge — httpx cannot solve)
        # Rappler is a major PH news outlet covering Middle East & OFW repatriation
        url="https://www.rappler.com/world/middle-east/",
        tier="TIER1",
        indicator_ids=("I07",),
        keywords=("evacuation", "middle east", "uae", "repatriation", "ofw", "ofws", "philippine"),
        critical_keywords=("evacuation", "repatriation"),
        interval_min=30,
        priority="medium",
        collection_target="필리핀 대피 현황",
    ),
    SourceSpec(
        source_id="tier1_flightradar24",
        name="Flightradar24 News",
        url="https://www.flightradar24.com/blog/",
        tier="TIER1",
        indicator_ids=("I07", "I02"),
        keywords=("evacuation", "flight suspended", "airspace", "diversion", "uae"),
        critical_keywords=("flight suspended", "airspace", "evacuation"),
        tags=("air_update",),
        interval_min=30,
        priority="high",
        collection_target="다국적군 대피편 운항 정보",
    ),
    SourceSpec(
        source_id="tier1_flightaware_news",
        name="FlightAware News",
        url="https://blog.flightaware.com/",
        tier="TIER1",
        indicator_ids=("I07", "I02"),
        keywords=("evacuation", "flight suspended", "airspace", "delay", "uae"),
        critical_keywords=("flight suspended", "airspace", "evacuation"),
        tags=("air_update",),
        interval_min=30,
        priority="medium",
        collection_target="다국적군 대피편 운항 정보",
    ),
]


async def collect_tier1_signals(*, timeout_sec: float, now: datetime) -> tuple[list[dict], dict[str, dict]]:
    if os.getenv("PYTEST_CURRENT_TEST"):
        return [], {}
    return await collect_source_specs(TIER1_SPECS, timeout_sec=timeout_sec, checked_at=now)
